baseURL = 'https://ggrigorev.me/'
languageCode = 'en-us'
title = 'George Grigorev Blog'
theme = 'paper'

[params]
  # Used by the Paper theme for the header
  name = 'George Grigorev'
  bio = "Previously I worked at Together AI running distributed training on hundreds of GPUs and building evals. At Snap I developed multimodal LLMs that used 100M+ people worldwide, as well as doing diffusion model pre-training and building AI applications end-to-end and contributing to research. I have vast experience in both text, image, speech domains."
  mainSections = ['posts']
  color = 'linen'
  linkedin = 'george-grigorev'
  twitter  = 'iamgrigorev'
  github   = 'thepowerfuldeez'

[menu]
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/'
    weight = 10
  [[menu.main]]
    identifier = 'publications'
    name = 'Publications'
    url = '/publications/'
    weight = 20
  [[menu.main]]
    identifier = 'blog'
    name = 'Blog'
    url = '/posts/'
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
